name: Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        java: [11]
        jdk-distribution: [adopt]
        sbt-version: [1.1.0, 1.2.0, 1.5.0, 1.7.0, 1.9.0, 1.10.0, 1.10.10]
    name: Test on java ${{ matrix.java }}-${{ matrix.jdk-distribution }} SBT ${{ matrix.sbt-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }} on ${{ matrix.jdk-distribution }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.jdk-distribution }}

      - name: Set up SBT
        uses: sbt/setup-sbt@v1
        with:
          sbt-runner-version: ${{ matrix.sbt-version }}

      - name: Cache SBT
        uses: actions/cache@v4
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-java-${{ matrix.java }}-${{ matrix.jdk-distribution }}-${{ github.run_number }}
          restore-keys: ${{ runner.os }}-sbt-java-${{ matrix.java }}-${{ matrix.jdk-distribution }}-

      - name: Cache coursier cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-coursier-${{ github.run_number }}
          restore-keys: ${{ runner.os }}-coursier-

      - name: Checkout current
        run: git checkout . && git clean -df
      - name: Run tests
        run: sbt scripted
      - name: Clean caches
        run: |
          rm -fv ~/.ivy2/.sbt.ivy.lock
          find ~/.sbt        -name "*.lock"               -print -delete
          rm -rf ./.git
          rm -rf ./project/target #clean doesn't clean meta-build
